// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeTOsHGFDQA9NDVPHKzzw4oQ06RLc3qPM',
    appId: '1:77695892309:web:6134f09f6a33d107dd0ddc',
    messagingSenderId: '77695892309',
    projectId: 'mealsapp-f736d',
    authDomain: 'mealsapp-f736d.firebaseapp.com',
    storageBucket: 'mealsapp-f736d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBndzv6gJ7ieMyl4_i-t_tnTbhYuj3sjrE',
    appId: '1:77695892309:android:51fe14af212870c2dd0ddc',
    messagingSenderId: '77695892309',
    projectId: 'mealsapp-f736d',
    storageBucket: 'mealsapp-f736d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFzHIEt96VXYvBTKuz00K_DB3v9s-B-8',
    appId: '1:77695892309:ios:c3721723affff637dd0ddc',
    messagingSenderId: '77695892309',
    projectId: 'mealsapp-f736d',
    storageBucket: 'mealsapp-f736d.appspot.com',
    iosBundleId: 'com.example.mealsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFzHIEt96VXYvBTKuz00K_DB3v9s-B-8',
    appId: '1:77695892309:ios:ea30c98a70aab478dd0ddc',
    messagingSenderId: '77695892309',
    projectId: 'mealsapp-f736d',
    storageBucket: 'mealsapp-f736d.appspot.com',
    iosBundleId: 'com.example.mealsapp.RunnerTests',
  );
}
